project:
  type: website
  title: "Data Visualization"
  render:
    - modules/index.qmd
    # This renders modules, slides, and exercises into `_site`
    - modules/**/*.qmd

website:
  page-navigation: true
  sidebar:
    logo: static/logo.svg
    collapse-level: 1
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - text: '<strong>Modules</strong>'
      - section: "0. Visualization Intro"
        contents:
          - href: modules/module0/module0-01-data_visualization.qmd
          - href: modules/module0/module0-02-prerequisite_confirmation.qmd
      - section: "1. Why Visualize Data?"
        contents:
          - href: modules/module1/module1-00-module-learning-outcomes.qmd
          - href: modules/module1/module1-01-what_is_data_visualization.qmd
          - href: modules/module1/module1-02-true_or_false_data_visualization.qmd
          - href: modules/module1/module1-03-how_can_we_visualize_data.qmd
          - href: modules/module1/module1-04-test_your_knowledge_visualization_libraries.qmd
          - href: modules/module1/module1-07-aggregations_lines_and_layers.qmd
          - href: modules/module1/module1-08-questions_on_how_plots_are_created.qmd
          - href: modules/module1/module1-11-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    transition: slide
    show-notes: true
    slide-number: true
    width: 100%
    theme: styles.scss
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    code-line-numbers: false
    code-copy: true
    progress: false
    execute:
      echo: true
