project:
  type: website
  title: "Data Visualization"
  render:
    # This renders modules, slides, and exercises into `_site`
    - modules/**/*.qmd
    - modules/index.qmd
  resources:
    - styles.scss
    - src/utils.py
    - data
  execute-dir: project

pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Visualization Intro**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
          - href: modules/module0/module0-01-data_visualization.qmd
          - text: '&nbsp;&nbsp; 1.1. Prerequisite confirmation'
            href: modules/module0/module0-02-prerequisite_confirmation.qmd
      - section: "**M1. Why Visualize Data?**"
        contents:
          - href: modules/module1/module1-00-module-learning-outcomes.qmd
          - href: modules/module1/module1-01-what_is_data_visualization.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-true_or_false_data_visualization.qmd
          - href: modules/module1/module1-03-how_can_we_visualize_data.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module1/module1-04-test_your_knowledge_visualization_libraries.qmd
          - href: modules/module1/module1-07-aggregations_lines_and_layers.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module1/module1-08-questions_on_how_plots_are_created.qmd
          - href: modules/module1/module1-11-what_did_we_just_learn.qmd
      - section: "**M2. Visual Encoding Channels**"
        contents:
          - href: modules/module2/module2-00-module_learning_outcomes.qmd
          - href: modules/module2/module2-01-effective_use_of_visual_channels.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module2/module2-02-true_or_false_effective_visual_channels.qmd
          - href: modules/module2/module2-03-area_charts.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module2/module2-04-true_or_false_area_and_lines.qmd
          - href: modules/module2/module2-05-bar_charts_and_histograms.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module2/module2-06-true_or_false_bars_and_histograms.qmd
          - href: modules/module2/module2-07-creating_subplots_via_faceting.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module2/module2-08-true_or_false_facets.qmd
          - href: modules/module2/module2-09-what_did_we_just_learn.qmd
      - section: "**M3. Visualizing Distributions**"
        contents:
          - href: modules/module3/module3-00-module_learning_outcomes.qmd
          - href: modules/module3/module3-01-how_to_visualize_data_from_a_single_column.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module3/module3-02-true_or_false_distributions.qmd
          - href: modules/module3/module3-03-visualize_distributions_with_density_plots.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module3/module3-04-true_or_false_distributions.qmd
          - href: modules/module3/module3-05-comparing_multiple_distributions.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module3/module3-06-true_or_false_many_distributions.qmd
          - href: modules/module3/module3-07-what_did_we_just_learn.qmd
      - section: "**M4. Distributions and EDA**"
        contents:
          - href: modules/module4/module4-00-module_learning_outcomes.qmd
          - href: modules/module4/module4-01-visualizing_multidimensional_distributions.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module4/module4-02-true_or_false_plotting_multiple_numerical_columns.qmd
          - href: modules/module4/module4-03-visualizing_categorical_distributions.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module4/module4-04-return_of_the_pokemon.qmd
          - href: modules/module4/module4-05-exploratory_data_analysis.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module4/module4-06-true_or_false_eda.qmd
          - href: modules/module4/module4-07-eda_on_categorical_data.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module4/module4-08-true_or_false_categorical_columns.qmd
          - href: modules/module4/module4-09-what_did_we_just_learn.qmd
      - section: "**M5. Plots for Communication**"
        contents:
          - href: modules/module5/module5-00-module_learning_outcomes.qmd
          - href: modules/module5/module5-01-effective_figures_for_communication.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module5/module5-02-true_or_false_is_it_effective.qmd
          - href: modules/module5/module5-03-descriptive_titles_and_labels.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module5/module5-04-true_or_false_titles_and_formatting.qmd
          - href: modules/module5/module5-05-defining_and_transforming_axis_ranges.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module5/module5-06-true_or_false_transformations.qmd
          - href: modules/module5/module5-07-effective_use_of_colour_categorical_data.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module5/module5-08-true_or_false_color_coordination.qmd
          - href: modules/module5/module5-09-effective_use_of_colour_quantitative_data.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module5/module5-10-true_or_false_colouring_in_the_blank.qmd
          - href: modules/module5/module5-11-annotating_with_text_and_colour.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module5/module5-12-true_or_false_colouring_in_black_or_white.qmd
          - href: modules/module5/module5-13-what_did_we_just_learn.qmd
      - section: "**M6. Stories, Maps and Layouts**"
        contents:
          - href: modules/module6/module6-00-module_learning_outcomes.qmd
          - href: modules/module6/module6-01-telling_stories_with_visualization.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module6/module6-02-true_or_false_once_upon_a_time.qmd
          - href: modules/module6/module6-03-visualizing_geographical_data.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module6/module6-04-true_or_false_getting_geo_with_it.qmd
          - href: modules/module6/module6-05-figure_layouts.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module6/module6-06-true_or_false_concatenating_plots.qmd
          - href: modules/module6/module6-07-what_did_we_just_learn.qmd
      - section: "**M7. Chart Interactivity**"
        contents:
          - href: modules/module7/module7-00-module_learning_outcomes.qmd
          - href: modules/module7/module7-01-tooltips_zoom_and_selections.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module7/module7-02-true_or_false_getting_truthful_with_interactivity.qmd
          - href: modules/module7/module7-03-advanced_selections.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module7/module7-04-true_or_false_selecting_correctly.qmd
          - href: modules/module7/module7-05-using_widgets_to_control_selections.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module7/module7-06-true_or_false_controls.qmd
          - href: modules/module7/module7-07-sharing_altair_visualizations.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module7/module7-08-true_or_false_saving_and_sharing.qmd
          - href: modules/module7/module7-09-what_did_we_just_learn.qmd
      - section: "**Module Closing Remarks**"
        contents:
          - href: modules/module8/module8-00-congratulations.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true
