project:
  type: website
  title: "Data Visualization"
  render:
    # This will render modules, slides, and exercises into _site
    - modules/**/*.qmd
resources:
  - static/

website:
  page-navigation: true
  sidebar:
    collapse-level: 1
    style: "docked"
    search: true
    contents:
      - text: 'Course Intro'
        href: modules/index.qmd
      - section: "0. Visualization Intro"
        contents:
          - href: modules/module0/module0-01-data_visualization.qmd
          - href: modules/module0/module0-02-prerequisite_confirmation.qmd
      - section: "1. Why Visualize Data?"
        contents:
          - href: modules/module1/module1-00-module-learning-outcomes.qmd
          - href: modules/module1/module1-01-what_is_data_visualization.qmd
          - href: modules/module1/module1-02-true_or_false_data_visualization.qmd
          - href: modules/module1/module1-03-how_can_we_visualize_data.qmd
          - href: modules/module1/module1-04-test_your_knowledge_visualization_libraries.qmd
          - href: modules/module1/module1-07-aggregations_lines_and_layers.qmd
          - href: modules/module1/module1-08-questions_on_how_plots_are_created.qmd
          - href: modules/module1/module1-11-what_did_we_just_learn.qmd

format:
  html:
    grid:
      sidebar-width: 350px
      body-width: 1200px
      margin-width: 400px
