project:
  type: website
  title: "Data Visualization"
  render:
    - modules/index.qmd
    - modules/module0-01-data_visualization.qmd
    - modules/module0-02-prerequisite_confirmation.qmd
    - modules/module1-00-module-learning-outcomes.qmd
    - modules/module1-01-what_is_data_visualization.qmd
    - modules/module1-02-true_or_false_data_visualization_v1.qmd
    - modules/module1-03-how_can_we_visualize_data.qmd
    - modules/module1-04-test_your_knowledge_visualization_libraries.qmd
    - modules/module1-07-aggregations_lines_and_layers.qmd
    - modules/module1-08-questions_on_how_plots_are_created.qmd
    - modules/module1-11-what_did_we_just_learn.qmd
resources:
  - static/
  - modules/slides/

website:
  page-navigation: true
  sidebar:
    collapse-level: 1
    style: "docked"
    search: true
    contents:
      - text: 'Course Intro'
        href: modules/index.qmd
      - section: "0. Visualization Intro"
        contents:
          - text: "1. Data Visualization"
            href: modules/module0-01-data_visualization.qmd
          - text: "2. Prerequisite Confirmation"
            href: modules/module0-02-prerequisite_confirmation.qmd
      - section: "1. Why Visualize Data?"
        contents:
          - text: "0. Module Learning Outcomes"
            href: modules/module1-00-module-learning-outcomes.qmd
          - text: "1. What is Data Visualization"
            href: modules/module1-01-what_is_data_visualization.qmd
          - text: "2. Exercises"
            href: modules/module1-02-true_or_false_data_visualization_v1.qmd
          - text: "3. How can we visualize data?"
            href: modules/module1-03-how_can_we_visualize_data.qmd
          - text: "4. Exercises"
            href: modules/module1-04-test_your_knowledge_visualization_libraries.qmd
          - text: "5. Aggregations, Lines, and Layers"
            href: modules/module1-07-aggregations_lines_and_layers.qmd
          - text: "6. Exercises"
            href: modules/module1-08-questions_on_how_plots_are_created.qmd
          - text: "7. What did we just learn?"
            href: modules/module1-11-what_did_we_just_learn.qmd


format:
  html:
    grid:
      sidebar-width: 350px
