name: 'viz-oer'
channels:
    - conda-forge
    - r
    - defaults
dependencies:
    - python=3.12.*
    - pip
    - ipykernel
    - altair-all
    - vega_datasets
    - quarto
    - r-base>=4.1
    - r-essentials
    - r-devtools
    - r-gert
    - r-usethis
    - r-startup
    - r-reticulate
    - r-knitr
    - r-rmarkdown
