---
format: html
---

<script src='../../src/quiz.js'></script>  

# 1.1. Exercises

## True or False: Data Visualization

<div id='mcq1'></div> 
<script>
    generateQuiz(
        'mcq1', 
        'True or False',  
        'Depending on what is trying to be communicated, some visual channels do a better job than others',  
        { 
        'True': 'In the slides, we saw that position or length do a better job when comparing size.',
        'False': 'Do you find it easier to compare size using area? Or with length?'
        },
        'True',  
    );
</script>

<div id='mcq2'></div> 
<script>
    generateQuiz(
        'mcq2',
        'True or False',
        'There are 3 channels that can be used in visualizations: Texture, size and colour.',
        {
        'True': 'What about positions, angles, or shades? There are many channels and it would be difficult to quantify and effectively communicate texture.',
        'False': 'We saw that there are several other visual channels in addition to texture, size and colour! For example, position, angle, area, colour brightness or saturation, and volume!'
        },
        'False',
    );
</script>

## To 3D or Not to 3D?

<div id='mcq3'></div> 
<script>
    generateQuiz(
        'mcq3', 
        'Question 1',  
        'Which of the following is <strong>NOT</strong> a reason to avoid plotting in 3 dimensions?',  
        { 
        'Plotting in 3D can distort the data depending on the view.': 'This is exactly why 3D plots should be avoided!',
        'Plotting in 3D can be time consuming.': 'Plotting 3D can be quick to do depending on the tool.',
        '3D plots can be more difficult to read than in 2D plots.': 'As we saw in the example, a 3rd dimension can reduce the effectiveness of a plot since it’s harder to read.',
        '3-dimensions can reduce the clarity of a plot.': 'With bar charts, we saw that the observations on the plot appeared less than the true values.'
        },
        'Plotting in 3D can be time consuming.',  
    );
</script>

<div id='mcq4'></div> 
<script>
    generateQuiz(
        'mcq4', 
        'Question 2',  
        'Are there acceptable times to present a 3D plot?',  
        { 
            'No, never.': 'Hang on now...',
            'Yes, when the system we are presenting is naturally 3 dimensional.': 'What about the blood vessel example we saw?',
            'Yes, they can be effective in cases when it is important to convey real 3D objects and/or data mapped onto them. Examples include topographical Maps and biological protein structures. Making such visualizations interactive, or providing animations of them helps the audience more easily see where the different graphical features are located in the 3D space.': '',
            'Yes, if we can animate it.': 'This can help, but it’s not always acceptable.'
        },
        'Yes, they can be effective in cases when it is important to convey real 3D objects and/or data mapped onto them. Examples include topographical Maps and biological protein structures. Making such visualizations interactive, or providing animations of them helps the audience more easily see where the different graphical features are located in the 3D space.',  
    );
</script>


