---
format: revealjs
title: Congratulations on completing Data Visualization!
title-slide-attributes:
  data-notes: |
---

## You did it!

We covered a lot of ground but you managed to finished all 7 Modules. It's important to celebrate this success. 

## Attribution

- Material from UBC's <a href="https://github.com/UBC-MDS/DSCI_531_viz-1" target="_blank">DSCI 531: Data Visualization I</a> by <a href="https://joelostblom.com/" target="_blank">Joel Ostblom</a>
- Material from UBC's <a href="https://github.com/UBC-MDS/DSCI_532_viz-2" target="_blank">DSCI 532: Data Visualization II</a> by <a href="https://joelostblom.com/" target="_blank">Joel Ostblom</a>.

## Special Thanks 

Not only did you put in a lot of work by completing this course, but many people did too by helping make this course possible. 

Special thanks must be attributed to the following individuals and organizations (in alphabetical order):

- <a href="https://www.tomasbeuzen.com/" target="_blank"> Tom Beuzen</a> 
- <a href="https://betatim.github.io/" target="_blank">Tim Head</a>  
- <a href="https://www.linkedin.com/in/junghoo/" target="_blank">Junghoo Kim</a>
- <a href="https://ines.io/" target="_blank">Ines Montani</a> 
- <a href="https://www.tiffanytimbers.com/" target="_blank"> Tiffany Timbers</a> 
- <a href="https://www.linkedin.com/in/elijah-willie-203845b9/?originalSubdomain=ca" target="_blank">Elijah Willie</a>


- The Master of Data Science Program at UBC
- Our friends, family and colleagues for supporting us and cheering us on!


## About Us

<br>

### Tiffany Timbers 

- Website: <a href="https://www.tiffanytimbers.com/" target="_blank">www.tiffanytimbers.com</a> 
- Twitter: <a href="https://twitter.com/TiffanyTimbers" target="_blank">@TiffanyTimbers</a> 
<br>
<br>

### Joel Ostblom 

- Website: <a href="https://joelostblom.com/" target="_blank">https://joelostblom.com/</a> 
- Twitter: <a href="https://twitter.com/joelostblom" target="_blank">@joelostblom</a> 
<br>
<br>

### Hayley Boyce 

- Website: <a href="https://www.hayleyfboyce.com" target="_blank">www.hayleyfboyce.com</a>
- Twitter: <a href="https://twitter.com/hayleyfboyce" target="_blank">@HayleyFBoyce</a> 


# Good luck on applying your new skills!