---
format: 
  html:
    page-layout: full
---
## Test Your Knowledge: Visualization Libraries

**Question 1**<br>
*What is another way of describing high-level visualization libraries?*

a) Imperative
a) Declarative
a) Immediate
a) Definitive


::: {.callout-tip title="Answer" collapse="true"}
The correct answer is **"Declarative"**.<br>
- "Imperative" refers to low-level plotting.<br>
- "Immediate" and "Definitive" are also incorrect choices—we included them as distractors.
:::

**Question 2**<br>
*What kind of components are combined in declarative plotting to create visualizations?*

a) Dictionary Keys
a) Block Components
a) Grammatical Components
a) Grouping Components

::: {.callout-tip title="Answer" collapse="true"}
The correct answer is **"Grammatical Components"**.<br>
Exlanation for the incorrect answer choices:<br>
- "Dictionary Keys": This refers to a data structure, not a plotting structure.<br>
- "Block Components": Consider a more language-oriented approach.<br>
- "Grouping Components": This term doesn’t have a clear definition—we made it up!
:::