---
format: html
---

<script src='../../src/quiz.js'></script>  <!-- Only needed once per page -->

# 3.1. Exercises

## Test Your Knowledge: Visualization Libraries

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'Which function do we need to use to superimpose plots in Altair?',
        {
        'Overlay': 'Not quite right',
        'Layer': '',
        'Panel': 'Not quite right',
        },
        'Layer',
    );
</script>

<div id='mcq2'></div>
<script>
    generateQuiz(
        'mcq2',
        'Question 2',
        'Line plots are often preferable to point plots when visualizing trends over time because…',
        {
        'The lines make the plot more visually appealing.': 'There is more to plots then just being visually appealing.',
        'Line plots are faster to create.': 'They both take approximately the same time to create. ',
        'The line makes it easy to see which values are connected in the same group and its slope facilitates our interpretation of the overall trend.': '',
        },
        'The line makes it easy to see which values are connected in the same group and its slope facilitates our interpretation of the overall trend.',
    );
</script>
