---
params:
  dynamictitle: "module6_03"
title: "`r params$dynamictitle`"
output:
  md_document:
    variant: gfm
    pandoc_args: "--markdown-headings=atx"
---

```{r setup, include=FALSE}
source('../../../../slide-setup.R')
# Remember to also manually update the YAML title above
```

type: slides


# Figure composition

Notes:
In this module we will see how we layout plots together
in a panel, instead of showing only one at a time.

---

## Loading in the data

```{python echo=FALSE}
import altair as alt
import pandas as pd
from vega_datasets import data

state_map = alt.topo_feature(data.us_10m.url, 'states')
state_pop = pd.read_csv('data/us_population_and_coordinates.csv')

choropleth = (alt.Chart(state_map).mark_geoshape().transform_lookup(
    lookup='id',
    from_=alt.LookupData(state_pop, 'id', ['population']))
.encode(color='population:Q')
.project(type='albersUsa')).properties(height=200, width=300)

us_map = (alt.Chart(state_map).mark_geoshape(color='lightgray', stroke='white')
          .project(type='albersUsa'))

points = alt.Chart(state_pop).mark_circle().encode(
    longitude='longitude',
    latitude='latitude',
    size='population')

points_on_map = us_map + points
```

Notes:
On this slide we are recreating the choropleth and pointplot map
from the end of the last slide deck.
We are saving these as objects so that we can use them to practice
laying out plots together in a panel on the following slides.

TODO fix so that this code shows up correctly on the slide

---

## Placing plots next to each other allows us to make more direct comparisons

```{python}
choropleth | points_on_map
```

Notes:
To place these two plots side by side,
we can use the pipe (`|`) operator.
You may have already seen us using this operator occasionally in previous modules.

We could also accomplish the same thing by using the `alt.hconcat(choropleth, points_on_map)` 
syntax. Here, we chose however to opt for the pipe operator as it is more efficient (keystroke-wise). 

Note where the legends for these plots get placed when we do this; they are placed to the right of both plots.

---

## Plots can also be concatenated vertically

```{python}
choropleth & points_on_map
```

Notes:
To place plots in a panel stacked vertically instead of horizontally,
we can use the ampersand (`&`) operator.

We could also have used the `alt.vconcat(choropleth, points_on_map)`,
but again, using this operator is a bit more efficient.

---

## Vertical and horizontal concatenation can be combined

```{python}
bars = alt.Chart(state_pop).mark_bar().encode(
    y='population',
    x=alt.Y('state', sort='y', title=None),
    color='population').properties(height=100, width=625)

points_on_map | choropleth & bars
```

Notes:
Often we want to create more complex figure layouts
where visualizations are stacked both horizontally and vertically.
Such layouts allow us to present connected, or related information near to one another,
and can be useful if there is a key comparison we want to make
between multiple visualizations. 

Yes, we could always place each visualization on its own slide or page 
(when sharing figures on paper),
however, our working memories are only so good. 
We often forget key details about visualizations we 
just saw when it is removed and we are presented with a new one.

In Altair,
we can create the figure layout
by combining the vertical and the horizontal concatenation operators.

In this slide,
we create a barplot of the population in each state
that we want to place under the two maps.
But as we can see in this slide,
this places the barplot under only the rightmost map.
Why is that?

---

## Parentheses can be used to indicate groupings in complex layouts

```{python}
bars = alt.Chart(state_pop).mark_bar().encode(
    y='population',
    x=alt.Y('state', sort='y', title=None),
    color='population').properties(height=100, width=625)

(points_on_map | choropleth) & bars
```

Notes:
The reason that the plot in the previous slide did not look like we wanted it to, 
was that the `&` operator has higher priority than `|` operator.

The resulted in the choropleth and barplot being vertically concatenated
before the point map was horizontally concatenated.

What we really want is the horizontal concatenation between the maps 
to occur first, followed by the vertical concatenation of the barplot.

Just as we use parentheses in mathematics to change the default order 
of mathematical operations, we can use parentheses to change the default order 
of concatenation operations.

You can see an example of that in this slide,
where we place the parentheses around the `points_on_map | choropleth`
to force the horizontal concatenation between the maps 
to occur first, and that leads us to get the barplot to show up below both the maps
as desired.

---

## Titles can be added to each level of the layout

```{python}
centered_map_title = alt.TitleParams(text='Map comparison', anchor='middle')
((points_on_map | choropleth) .properties(title=centered_map_title) & bars).properties(title='US population by state')
```

Notes:
To make our visualization easier to interpret,
we can add descriptive titles.
These are often particularly important when we create more complex figures
since there are now several panels within each figure to keep track of.

This doesn't mean that each panel absolutely needs a title,
but when in doubt it is better to add one title too many than one too few.

---

# Let's apply what we learned!

Notes: <br>
