---
params:
  dynamictitle: "module1_03"
title: "`r params$dynamictitle`"
output:
  md_document:
    variant: gfm
    pandoc_args: "--atx-headers"
---

```{r include=FALSE}
# Update the title in the YAML preamble for each slide show
knitr::opts_chunk$set(
    echo = TRUE,
    base.dir = ".",
    base.url = "/",
    fig.path = paste("../../../../static/module1/", params$dynamictitle,"/", sep = ""))

source('../../../../slide-setup.R')
```

type: slides

# Lines and layers

Notes:
In this slide deck we will see how to create lineplots
and how to combine line and point plots together
via layers in Altair.

---

## Visualizing trends over time with scatter plots is not ideal

```{python}
import altair as alt
from vega_datasets import data

cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Year',
    y='Miles_per_Gallon')
```

Notes:
We could use the point mark to visualize trends over time,
such as how the miles per gallon has changes over the years.
However,
it is hard to see a general trend in this data.

---

## Visualizing trends over time with line plots makes them easier to interpret

```{python}
alt.Chart(cars).mark_line().encode(
    x='Year',
    y='Miles_per_Gallon')
```

Notes:
Trends are often more effectively visualized with lines,
since the slope can help us determine the change in y over time.
Let's try switching our mark to a line.

Oh oh, something is wrong.
Since there are multiple values per year,
the line connects them vertically,
which is not what we want here.

---

## Visualizing an aggregate for each year gives a better overview

```{python}
yearly_avg_gallons = cars.groupby('Year')['Miles_per_Gallon'].mean().reset_index()

alt.Chart(yearly_avg_gallons).mark_line().encode(
    x='Year',
    y='Miles_per_Gallon')
```

Notes:
Instead,
what we want is to aggregate the data
so that there is only one point per year
(e.g. by calculating the mean or median).
We could wrangle the data manually in pandas before plotting it
like in this slide.
This plot looks much better
and it is easy for us to visualize the change over time.

---

## Performing the aggregation in Altair directly is more convenient

```{python}
alt.Chart(cars).mark_line().encode(
    x='Year',
    y='mean(Miles_per_Gallon)')
```

Notes:
Instead of doing this two step process with pandas,
we could aggregate right inside Altair.
To get the mean of a column,
wrap it in a string that says `'mean()'` as in this slide.

That is a convenient shortcut!
Many common aggregations and transformations
are available directly in Altair via this syntax,
[more info can be found in the documentation
including a table with all available aggregations](https://altair-viz.github.io/user_guide/encoding.html#binning-and-aggregation).

---

## Grouping by a column before aggregating creates one aggregate per group

```{python}
alt.Chart(cars).mark_line().encode(
    x='Year',
    y='mean(Miles_per_Gallon)',
    color='Origin')
```

Notes:
Altair understands that when we specify another encoding channel
(such as `color`)
together with an aggregation,
we want to take the mean of each group
in the color channel separately.
This works just like if we had done the following in pandas
`groupby('Origin').mean('Miles_per_Gallon)`,
and gives us one line per group in this plot.

---

## Comparing points with lines for grouped charts reveals the advantages of using lines

```{python}
alt.Chart(cars).mark_point().encode(
    x='Year',
    y='mean(Miles_per_Gallon)',
    color='Origin')
```

Notes:
This is the same plot as on the previous slide,
but using points instead of line
in order to illustrate how much harder it is to follow
the trends over time without the lines connecting the values together.

---

## Combining a line with a set of points via layers

```{python}
line = alt.Chart(cars).mark_line().encode(
    x='Year',
    y='mean(Miles_per_Gallon)')

point = alt.Chart(cars).mark_point().encode(
    x='Year',
    y='mean(Miles_per_Gallon)')

line + point
```

Notes:
As we've seen above, the Altair `Chart` object represents a plot with a single mark type.
What about more complicated diagrams, involving multiple charts or layers?
Using a set of *view composition* operators,
Altair can take multiple chart definitions
and combine them to create more complex views.

To augment this plot,
we might like to add `point` marks for each averaged data point.
We can start by defining each chart separately:
first a line plot,
then a scatter plot.
We can then use the `alt.layer` function or its shortcut operator `+` (plus)
to combine the two into a layered chart.
Here we use the shorthand `+` (plus) operator to invoke layering.

---

## Building upon previous plots can save time when combining charts

```{python}
line = alt.Chart(cars).mark_line().encode(
    x='Year',
    y='mean(Miles_per_Gallon)')

line + line.mark_point()
```

Notes:
We can also create this chart by *reusing* and *modifying* a previous chart definition!
Rather than completely re-write a chart,
we can start with the line chart,
then invoke the `mark_point` method
to generate a new chart definition with a different mark type:
We could also have typed `mark_line(point=True)`,
which is a special case for getting points on a line
since it is such a common operation.

---

## Showing raw values together with the mean is often helpful

```{python}
line = alt.Chart(cars).mark_line().encode(
    x='Year',
    y='mean(Miles_per_Gallon)')

line + line.mark_point().encode(y='Miles_per_Gallon')
```


Notes:
We can also create a layer with one point per observations,
and with a line for the average values.
For this we need to use `encode` again
after creating the first plot,
to instruct Altair to use the raw vales
instead of the mean for the points.
(Note that the axis now has two labels,
we will see how to change that next lecture.)

---

## All encodings of the base chart are propagated unless they are overwritten

```{python}
line = alt.Chart(cars).mark_line().encode(
    x='Year',
    y='mean(Miles_per_Gallon)',
    color='Origin')

line + line.mark_point().encode(y='Miles_per_Gallon')
```

Notes:
Adding color to the base chart propagates it to all the layers.
If we would only have added it to the point chart,
there would still have been a single line instead of three.

---

# Let's apply what we learned!

Notes: <br>
