project:
  type: website
  output-dir: "_site" 
  render:
    - content/module0-01-data_visualization.qmd
    - content/module0-02-prerequisite_confirmation.qmd
    - content/module1-01-what_is_data_visualization.qmd
resources:
  - static/

website:
  title: "Data Visualization"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Module 0"
        contents:
          - text: "Data Visualization"
            href: "content/module0-01-data_visualization.qmd"
          - text: "Prerequisite Confirmation"
            href: "content/module0-02-prerequisite_confirmation.qmd"
          - text: "Jupyter Basics"
            href: "content/module-0-introduction.qmd"
      - section: "Module 1"
        contents:
          - text: "What is Data Visualization"
            href: "content/module1-01-what_is_data_visualization.qmd"
          - text: "Jupyter Layout"
            href: "content/module-0-introduction.qmd"
      - section: "Crossrefs"
        contents:
          - text: "Markdown Crossrefs"
            href: "content/module-0-introduction.qmd"
          - text: "Knitr Crossrefs"
            href: "content/module-0-introduction.qmd"
          - text: "Jupyter Crossrefs"
            href: "content/module-0-introduction.qmd"
