project:
  type: website
  output-dir: "_site" 
  render:
    - content/module0-01-data_visualization.qmd
    - content/module0-02-prerequisite_confirmation.qmd
    - content/module1-00-module-learning-outcomes.qmd
    - content/module1-01-what_is_data_visualization.qmd
    - content/module1-02-true_or_false_data_visualization_v1.qmd
    - content/module1-02-true_or_false_data_visualization_v2.qmd
    - "content/module1-03-how_can_we_visualize_data.qmd"
    - "content/module1-04-test_your_knowledge_visualization_libraries.qmd"
    - "content/module1-05-true_or_false_visualization_libraries.qmd"
    - "content/module1-07-aggregations_lines_and_layers.qmd"
resources:
  - static/

website:
  title: "Data Visualization"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Module 0"
        contents:
          - text: "Data Visualization"
            href: "content/module0-01-data_visualization.qmd"
          - text: "Prerequisite Confirmation"
            href: "content/module0-02-prerequisite_confirmation.qmd"
      - section: "Module 1"
        contents:
          - text: Module Learning Outcomes
            href: "content/module1-00-module-learning-outcomes.qmd"
          - text: "What is Data Visualization"
            href: "content/module1-01-what_is_data_visualization.qmd"
          - text: "True or False: Data Visualization V1"
            href: "content/module1-02-true_or_false_data_visualization_v1.qmd"
          - text: "True or False: Data Visualization V2"
            href: "content/module1-02-true_or_false_data_visualization_v2.qmd"
          - text: "How can we visualize data?"
            href: "content/module1-03-how_can_we_visualize_data.qmd"
          - text: "Test Your Knowledge: Visualization Libraries"
            href: "content/module1-04-test_your_knowledge_visualization_libraries.qmd"
          - text: "True or False: Visualization Libraries"
            href: "content/module1-05-true_or_false_visualization_libraries.qmd"
          - text: "Aggregations, Lines, and Layers"
            href: "content/module1-07-aggregations_lines_and_layers.qmd"

format:
  html:
    toc: true  
    number-sections: true  