project:
  type: website
  output-dir: "_site"  
resources:
  - static/


website:
  title: "Data Visualization"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Module 0"
        contents:
          - text: "Data Visualization"
            href: "content/module-0-data_visualization.qmd"
          - text: "Prerequisite Confirmation"
            href: "content/module-0-introduction.qmd"
          - text: "Jupyter Basics"
            href: "content/module-0-introduction.qmd"
      - section: "Module 1"
        contents:
          - text: "Markdown Layout"
            href: "content/module-0-introduction.qmd"
          - text: "Jupyter Layout"
            href: "content/module-0-introduction.qmd"
      - section: "Crossrefs"
        contents:
          - text: "Markdown Crossrefs"
            href: "content/module-0-introduction.qmd"
          - text: "Knitr Crossrefs"
            href: "content/module-0-introduction.qmd"
          - text: "Jupyter Crossrefs"
            href: "content/module-0-introduction.qmd"