---
params:
  dynamictitle: "module5_08"
title: "`r params$dynamictitle`"
output:
  md_document:
    variant: gfm
    pandoc_args: "--markdown-headings=atx"
---

```{r setup, include=FALSE}
source('../../../../slide-setup.R')
# Remember to also manually update the YAML title above
```

type: slides


# Defining and transforming axis ranges

Notes:
In this slide deck,
we will see how defining an explicit axis range
is beneficial when we need to zoom into a region of a plot,
and how log transforming an axis can help increase resolution of small values.

---

## Read in the data containing the daily sum of donations to Wikipedia in 2020

```{python include=FALSE}
import pandas as pd

donations = (
    pd.read_csv("https://frdata.wikimedia.org/donationdata-vs-day.csv", parse_dates=['date'])
    .query('2020 < date < 2021')
    .assign(week_day=lambda df: df['date'].dt.day_name().str[:3]))
donations.to_csv('data/donations.csv', index=False)
```

```{python}
import pandas as pd
import altair as alt

donations = pd.read_csv('data/donations.csv', parse_dates=['date'])
alt.Chart(donations, title='Wikipedia donations peak during Christmas').mark_circle().encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'), title='Amount donated per day'))
```

Notes:
We will be working with a data set that contains the daily sum
of all donations received by Wikipedia
in the year 2020.
When do you think Wikipedia
receives the largest amount of donated money?

From this overview of the data
we can see that the most money
is donated around Christmas and new years.

There also seems to be a higher amount donated during the fall
than during spring and winter.

However,
we cannot see exactly which values the data points during the first half of the year has.
Are they close to zero? Or 10,000?
We can't know from looking at this plot.

---

## We can zoom in to highlight a region of an axes by filtering the data

```{python}
title_text = 'Wikipedia donations peak during Christmas'
donations_2020_until_july = donations[donations['date'].between("2020", "2020-07")]
alt.Chart(donations_2020_until_july, title=title_text).mark_circle().encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'), title='Amount donated per day'))
```

Notes:
Zooming in on an axis is useful
when we want to highlight a certain region.
The easiest way to achieve this
is often to filter the data with pandas
before passing it `alt.Chart` as in this example.

---

## We can zoom in to highlight a region of an axes

```{python}
alt.Chart(donations_2020_until_july, title=title_text).mark_circle(clip=True).encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'),
          title='Amount donated per day',
          scale=alt.Scale(domain=[0, 100_000])))
```

Notes:
It is not always practical to filter the data,
so it is good to know how to change the axis range directly in Altair.
For this,
we could modify the domain of the axis' scale.

When we modify the scale,
we need to set `clip=True` inside the mark.
Without it,
we would still see the circles extending beyond the range of the chart.

This also serves as a reminder
to think twice about limiting the displayed points
because it can skew the perception of the data
as we saw with bar chart in the previous slide deck.

When we used `alt.Axis` previously,
the changes we made were cosmetic,
such as tick numbers,
label formatting etc.

Now that were are modifying the range of the actual displayed values,
we need to use `alt.Scale` instead.
Here we place `alt.Scale` within `alt.Y`
to specify that we are changing the scale of the y-axis.
It also works the same way with `alt.Color` and `alt.Size`,
which changes the display of the these in the legend.

After zooming in on the y-axis as in this slide,
we can more clearly see the variation in the lower value data points.
We can see that more money is often donated at the beginning of each month,
except for the month of July.

---

## Axes can be anchored to the data range instead of to zero without explicitly setting the domain

```{python}
alt.Chart(donations[donations['sum'] > 2.5e6]).mark_circle().encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'), title='Amount donated per day'))
```

Notes:
You might have noticed from previous modules that Altair often includes 0 in the axis,
even if our data does not have any values close to 0.
The reason for this is to enforce good habits 
and not create for example bar plot that are cut off
which makes difference appear much bigger than they actually are.

However,
there are also good reasons for setting the range based on the extent of the data.
when your data is compressed in a narrow range far from zero,
e.g. plotting time on one axis
and having all observations fall between 10 and 11 in the evening.

In this slide we can see that showing only the days with high total donations
only uses about half of the vertical space available in the chart.

---

## Axis can be anchored to the data range instead of to zero without explicitly setting the domain

```{python}
alt.Chart(donations[donations['sum'] > 2.5e6]).mark_circle().encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'), title='Amount donated per day', scale=alt.Scale(zero=False)))
```

Notes:
If we wanted to use the full range,
we could set the domain explicitly like before,
but the shortcut `zero=False` allows us to adjust the axis
to the min and max values of the data with less typing.

We need to be careful when doing this
since it can make small difference appear much bigger than they are.
On the previous slide 
the point at 4.7M was about twice as far from the x-axis as the point at 2.5M from the x-axis.
In this slide it is about 20 times further away from the x-axis!

---

## Large values can hide variation among the rest of the data

```{python}
alt.Chart(donations, title='Wikipedia donations peak during Christmas').mark_circle().encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'), title='Amount donated per day'))
```

Notes:
So far,
we have seen how we can zoom in 
to reveal detail of a specific region of the chart.

What if we want to show all the chart,
but still be able to see details for the days with lower total donations?

---

## Altair allows us to interactively zoom in and out of the plot

```{python}
alt.Chart(donations, title='Wikipedia donations peak during Christmas').mark_circle().encode(
    alt.X('date', title=None),
    alt.Y('sum', axis=alt.Axis(format='$s'), title='Amount donated per day')).interactive()
```

Notes:
One of Altair's stong suites
is that it is not limited to static visualizations.

By simply appending the `interactive()` method to our chart 
we can use the mouse to zoom by scrolling and pan by clicking and dragging!

This allows us to interactively explore the data
and zoom in on the points of interest as needed.
We will learn more about interactive visualizations in the last module,
this is just a sample of what is possible.

Neat ey?
Now let's get back to the current task at hand,
how can we solve the problem of a large axis range in a static figure?
As sometimes,
we need a static figure,
e.g. when we print images on paper or display them in a static file-type, such as a PDF.

---

## A log transformed axis can reveal detail across a large range of values

```{python}
alt.Chart(donations).mark_point().encode(
    alt.X('date', title=None),
    alt.Y('sum', title='Amount donated per day (log-transformed)',
          axis=alt.Axis(format='$s'), scale=alt.Scale(type='log')),
    alt.Tooltip('week_day'))
```

Notes:
By applying a logarithmic (log) transformation to the y-axis,
we're able to increase the range used for the smaller values
by compressing the space used for larger values.

This means that log transformations are useful
when there are large differences in the data values,
such as in our case here.

Log scales are also useful to show data that has been obtained from multiplication or division,
such as ratios.

The default log transformaton in Altair uses the base 10
which is the most common choice.
Every step on a log scale is referred to
as a difference of an "order of magnitude".

It is important to remember that we log scaled axes
are not as easy to interpret as linear ones,
and it is easy to underestimate actual the difference between large and small values.

This is especially true
when creating figures for communication
with the general public
rather than in a subject area
where participants might be more used
to seeing this transformation.

If you find yourself situation
make sure that you clearly label the axis as log-transformed
and add any explanatory text to help a general audience 
interpret your visualization.

---

## The log transformation does not work for data containing the value zero

```{python}
donations.loc[0, 'sum'] = 0
alt.Chart(donations).mark_point().encode(
    alt.X('date', title=None),
    alt.Y('sum', title='Amount donated per day (log-transformed)',
          axis=alt.Axis(format='$'), scale=alt.Scale(type='log')))
```

Notes:
The way the logarithmic transform is defined
means that it cannot be calculated for the value 0.

We can see this if we artificially introduce a 0 in our dataset.

All the data points are compressed at the top,
because the log of 0 is interpreted as a value of negative infinity.

---

## The symlog transformation avoids the problem with zeroes in the data

```{python}
alt.Chart(donations).mark_point().encode(
    alt.X('date', title=None),
    alt.Y('sum', title='Amount donated per day (symlog-transformed)',
          axis=alt.Axis(format='$s'), scale=alt.Scale(type='symlog')))
```

Notes:
Fortunately there is a symmetrical variant of the log transformation (symlog)
which works around the issues with zeroes by defining a linear range for values close to 0,
and a logarithmic range all other values.

We can see that the y-axis looks different here
as it explicitly includes the value zero,
and the tick values are set differently for symlog
compared to the regular log transform.

---

## Remember to use the correct mark for your data

```{python}
alt.Chart(donations.drop(0)).mark_line().encode(
    alt.X('date', title=None),
    alt.Y('sum', title='Amount donated per day (log-transformed)',
          axis=alt.Axis(format='$s'), scale=alt.Scale(type='log')))
```

Notes:
In this slide we're dropping the artificial 0
we introduced earlier
to bring attention to another important aspect of visualization:
the choice of mark.

So far we have been plotting our timeseries data using circles.
This has been useful to illustrate the points above,
but it is not the most effective choice for visualizing temporal data.

By changing the mark to a line
it is much easier for us to follow the trend going from one point to another
and we can immediately spot a curios pattern!

What are those repeated ups and down?
Are those random fluctuations
or are there particular days of the month
where people are more likely to donate?

We will return to this data in the last slide deck of this module to find out!


```python

```

---

# Let's apply what we learned!

Notes: <br>
